# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: C++ Client CI with Maven

on:
  push:
    branches: 
      - master
      - 'rel/*'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: 
      - master
      - 'rel/*'
      - cluster_new
    paths-ignore:
      - 'docs/**'
        
jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        java: [11.0.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os}}
    defaults: 
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Check Apache Rat
        run: mvn -B apache-rat:check
      - name: Install Bison
        if: matrix.os == 'macos-latest'
        run: brew install bison
      - name: Chocolatey Action
        if: matrix.os == 'windows-latest'
        uses: crazy-max/ghaction-chocolatey@v1.4.0
      - name: Install Bison and Flex
        if: matrix.os == 'windows-latest'
        run: choco install winflexbison3
      - name: Test with Maven
        run:  mvn integration-test -P client-cpp -pl client-cpp,compile-tools,compile-tools/boost,compile-tools/thrift,server -am -Diotdb.test.skip=true -Dtsfile.test.skip=true -Djdbc.test.skip=true

